{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "consentos.secretName" . }}
  labels:
    {{- include "consentos.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret-key: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}
  postgresql-password: {{ .Values.secrets.postgresqlPassword | b64enc | quote }}
{{- end }}
