package com.consentos

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.io.IOException
import java.net.HttpURLConnection
import java.net.URL

// =============================================================================
// Protocol (Interface)
// =============================================================================

/**
 * Abstracts the network layer for testability.
 *
 * Implementations must be safe to call from any coroutine context.
 */
interface ConsentAPIProtocol {
    /**
     * Fetches the effective site configuration from the API.
     *
     * @param siteId The site identifier registered in the CMP dashboard.
     * @throws ConsentAPIException on network or server errors.
     */
    suspend fun fetchConfig(siteId: String): ConsentConfig

    /**
     * Posts a consent record to the server.
     *
     * @param payload The consent event payload.
     * @throws ConsentAPIException on network or server errors.
     */
    suspend fun postConsent(payload: ConsentPayload)
}

// =============================================================================
// Errors
// =============================================================================

/**
 * Errors that can be thrown by the CMP API client.
 */
sealed class ConsentAPIException(message: String, cause: Throwable? = null) :
    Exception(message, cause) {

    /** The constructed API URL is malformed. */
    class InvalidURL(url: String) :
        ConsentAPIException("The constructed API URL is invalid: $url")

    /** The server returned a non-2xx HTTP status code. */
    class UnexpectedStatusCode(val code: Int) :
        ConsentAPIException("The server returned an unexpected HTTP status code: $code.")

    /** The server response could not be decoded. */
    class DecodingFailure(cause: Throwable) :
        ConsentAPIException("Failed to decode the server response: ${cause.message}", cause)

    /** A network I/O error occurred (e.g. no connectivity). */
    class NetworkFailure(cause: Throwable) :
        ConsentAPIException("A network error occurred: ${cause.message}", cause)
}

// =============================================================================
// Consent Payload
// =============================================================================

/**
 * The request body sent when recording a consent event.
 */
@Serializable
data class ConsentPayload(
    @SerialName("site_id")     val siteId: String,
    @SerialName("visitor_id")  val visitorId: String,
    val platform: String = "android",
    val accepted: List<String>,
    val rejected: List<String>,
    @SerialName("consented_at") val consentedAt: String,  // ISO-8601 UTC
    @SerialName("banner_version") val bannerVersion: String? = null,
    @SerialName("user_agent") val userAgent: String? = null,
    @SerialName("tc_string")  val tcString: String? = null,
) {
    companion object {
        /**
         * Creates a [ConsentPayload] from a [ConsentState].
         *
         * @param siteId    The site identifier.
         * @param state     The consent state to serialise.
         * @param tcString  Optional TC string generated by [TCFStringEncoder].
         */
        fun from(
            siteId: String,
            state: ConsentState,
            tcString: String? = null,
        ): ConsentPayload? {
            val consentedAtMs = state.consentedAtMs ?: return null
            return ConsentPayload(
                siteId = siteId,
                visitorId = state.visitorId,
                accepted = state.accepted.map { it.value },
                rejected = state.rejected.map { it.value },
                consentedAt = formatIso8601(consentedAtMs),
                bannerVersion = state.bannerVersion,
                tcString = tcString,
            )
        }

        private fun formatIso8601(epochMs: Long): String {
            val sdf = java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", java.util.Locale.US)
            sdf.timeZone = java.util.TimeZone.getTimeZone("UTC")
            return sdf.format(java.util.Date(epochMs))
        }
    }
}

// =============================================================================
// Live Implementation
// =============================================================================

/**
 * HttpURLConnection-backed API client that communicates with the CMP API.
 *
 * Uses [kotlinx.coroutines.Dispatchers.IO] for all network calls so they are safe to
 * invoke from any coroutine context.
 *
 * @param apiBase The base URL of the CMP API (e.g. `https://api.example.com`).
 */
class ConsentAPI(private val apiBase: String) : ConsentAPIProtocol {

    private val json = Json {
        ignoreUnknownKeys = true
        encodeDefaults = true
    }

    private val userAgent = "ConsentOS-Android/${BuildConfig.SDK_VERSION} (Kotlin)"

    // -------------------------------------------------------------------------
    // ConsentAPIProtocol
    // -------------------------------------------------------------------------

    override suspend fun fetchConfig(siteId: String): ConsentConfig =
        withContext(Dispatchers.IO) {
            val urlStr = "$apiBase/api/v1/config/sites/$siteId/effective"
            val connection = openConnection(urlStr)
            try {
                connection.requestMethod = "GET"
                connection.setRequestProperty("Accept", "application/json")
                connection.setRequestProperty("User-Agent", userAgent)
                connection.connect()

                val code = connection.responseCode
                if (code !in 200..299) throw ConsentAPIException.UnexpectedStatusCode(code)

                val body = connection.inputStream.bufferedReader().readText()
                runCatching { json.decodeFromString<ConsentConfig>(body) }
                    .getOrElse { throw ConsentAPIException.DecodingFailure(it) }
            } catch (e: ConsentAPIException) {
                throw e
            } catch (e: IOException) {
                throw ConsentAPIException.NetworkFailure(e)
            } finally {
                connection.disconnect()
            }
        }

    override suspend fun postConsent(payload: ConsentPayload): Unit =
        withContext(Dispatchers.IO) {
            val urlStr = "$apiBase/api/v1/consent"
            val connection = openConnection(urlStr)
            try {
                connection.requestMethod = "POST"
                connection.setRequestProperty("Content-Type", "application/json")
                connection.setRequestProperty("Accept", "application/json")
                connection.setRequestProperty("User-Agent", userAgent)
                connection.doOutput = true

                val body = json.encodeToString(payload)
                connection.outputStream.bufferedWriter().use { it.write(body) }

                val code = connection.responseCode
                if (code !in 200..299) throw ConsentAPIException.UnexpectedStatusCode(code)
            } catch (e: ConsentAPIException) {
                throw e
            } catch (e: IOException) {
                throw ConsentAPIException.NetworkFailure(e)
            } finally {
                connection.disconnect()
            }
        }

    // -------------------------------------------------------------------------
    // Private Helpers
    // -------------------------------------------------------------------------

    @Throws(ConsentAPIException.InvalidURL::class)
    private fun openConnection(urlStr: String): HttpURLConnection {
        return runCatching { URL(urlStr).openConnection() as HttpURLConnection }
            .getOrElse { throw ConsentAPIException.InvalidURL(urlStr) }
    }
}
